name: .NET

on:
  workflow_dispatch:

jobs:
  build-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  gh-packages-deploy:
  
    needs: build-test
    runs-on: windows-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Pack
      run: dotnet pack -o ./out -c release
      
    - name: Push to GH Pakcages
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.GH_PACKAGES_PAT }} --source "https://nuget.pkg.github.com/LuanRoger/index.json" --skip-duplicate
    
  deploy-nuget:
  
    needs: build-test
    runs-on: windows-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Pack
      run: dotnet pack -o ./out -c release
      
    - name: Push to Nuget
      run: |
          cd out
          dotnet nuget push *.nupkg --api-key ${{ secrets.SC_NUGET_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
